from pydantic import BaseModel, Field
from typing import Optional, Dict

class EvaluationSubmission(BaseModel):
    question: str = Field(..., description="The original question asked by the user.")
    ai_response: str = Field(..., description="The answer generated by the AI that needs auditing.")
    reference_answer: Optional[str] = Field(None, description="The gold-standard true answer (Optional).")
    source_document: Optional[str] = Field(None, description="Raw context or source documentation text (Optional).")

class EvaluationResultResponse(BaseModel):
    submission_id: str
    status: str
    scores: Dict[str, float]
    verdict: str
    reasoning: Dict[str, str]

